environment:
  CYG_ROOT: C:\cygwin
  CYG_BASH: C:\cygwin\bin\bash
  CYG_CACHE: C:\cygwin\var\cache\setup
  CYG_EXE: C:\cygwin\setup-x86.exe
  CYG_MIRROR: http://cygwin.mirror.constant.com
  matrix:
    - SMALLTALK: Squeak32-trunk
    - SMALLTALK: Squeak32-5.2
    - SMALLTALK: Squeak32-5.1
    - SMALLTALK: Squeak32-5.0
    - SMALLTALK: Pharo32-alpha
    - SMALLTALK: Pharo32-5.0

matrix:
  fast_finish: true
  allow_failures:
    - SMALLTALK: Squeak32-trunk
    - SMALLTALK: Pharo32-alpha

platform:
  - x86

clone_depth: 5
build: false
version: "{build}"

install:
  - '%CYG_EXE% -dgnqNO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P unzip'

# Cygwin build script
#
# NOTES:
#
# The stdin/stdout file descriptor appears not to be valid for the Appveyor
# build which causes failures as certain functions attempt to redirect
# default file handles. Ensure a dummy file descriptor is opened with 'exec'.
test_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; bin/smalltalkci"'
